# https://github.com/groundhog2k/helm-charts/blob/master/charts/valkey/RELEASENOTES.md
SESSION_VALKEY_CHART_VERSION: 2.2.1
SESSION_VALKEY_IMAGE_VERSION: 9.0.0
SESSION_VALKEY_REDIS_EXPORTER_IMAGE_VERSION: v1.74.0
SESSION_VALKEY_REPLICAS: 3
