WITH_STORAGE: false
WITH_ERWINIDM: true
WITH_LDAP: false
WITH_TSP: false
WITH_MONGO_DATABASES: false
WITH_POSTGRES_DATABASES: false
WITH_BRANCH_POSTGRES_DB_MANAGEMENT: false
WITH_SCHULCLOUD_INIT: false
WITH_CALENDAR_INIT: false
WITH_OIDCMOCK: false
WITH_H5P_EDITOR: false
WITH_H5P_LIBRARY_MANAGEMENT: false
WITH_TLDRAW: true
WITH_API_ADMIN: true
WITH_MOIN_SCHULE: false
WITH_UNSYNCED_ENTITIES_DELETION: false
WITH_BOARD_COLLABORATION: false
WITH_MIGRATION_SYSTEMS: false
WITH_COMMON_CARTRIDGE: false
