WITH_STORAGE: false
WITH_ERWINIDM: false
WITH_LDAP: false
WITH_TSP_SYNC: false
WITH_MONGO_DATABASES: false
WITH_POSTGRES_DATABASES: false
WITH_BRANCH_POSTGRES_DB_MANAGEMENT: false
WITH_BRANCH_MONGO_DB_MANAGEMENT: false
WITH_BRANCH_TSP_REDIRECT_MANAGEMENT: false
WITH_SCHULCLOUD_INIT: false
WITH_CALENDAR_INIT: false
WITH_OIDCMOCK: false
WITH_H5P_EDITOR: true
WITH_H5P_LIBRARY_MANAGEMENT: true
WITH_TLDRAW: true
WITH_FILESTORAGE: true
WITH_API_ADMIN: true
WITH_MOIN_SCHULE: false
WITH_UNSYNCED_ENTITIES_DELETION: false
WITH_BOARD_COLLABORATION: false
WITH_MIGRATION_SYSTEMS: false
WITH_COMMON_CARTRIDGE: false
WITH_CLAMMIT: true
WITH_MEDIA_LICENSES: false
WITH_BILO_MEDIA_METADATA_SYNC: false
WITH_SCHULCONNEX_PROVISIONING: false
WITH_VIDIS_MEDIA_METADATA_SYNC: false
WITH_COLLABORA_OFFICE: true
WITH_FWU: false
