ANTIVIRUS_SCANFILE_REPLICAS: 1
ANTIVIRUS_WEBSERVER_REPLICAS: 1
API_LDAPSYNC_REPLICAS: 1
API_REPLICAS: 20
API_WORKER_REPLICAS: 10
CALENDAR_REPLICAS: 2
CLAMAV_REPLICAS: 1
CLIENT_REPLICAS: 10
ETHERPAD_NGINX_REPLICAS: 1
ETHERPAD_REPLICAS: 1
HYDRA_REPLICAS: 1
LIBREOFFICE_REPLICAS: 1
MAILDROP_REPLICAS: 1
NUXTCLIENT_REPLICAS: 4
RABBITMQ_REPLICAS: 3
REDIS_REPLICAS: 1
ROCKET_CHAT_REPLICAS: 5
SHD_REPLICAS: 1
API_FILE_STORAGE_REPLICAS: 5
AMQP_FILE_STORAGE_REPLICAS: 5
ERWINIDM_REPLICAS: 3
AMQP_FILE_PREVIEW_MIN_REPLICA_COUNT: 1
AMQP_FILE_PREVIEW_MAX_REPLICA_COUNT: 5
TLDRAW_CLIENT_REPLICAS: 3
TLDRAW_SERVER_REPLICAS: 3
ADMIN_API_SERVER_REPLICAS: 3
