SC_THEME: thr
SC_SHORTNAME: thr
SC_TITLE: Thüringer Schulcloud
SC_PRODUCTNAME: Thüringer Schulcloud
SC_NAV_TITLE: Thüringer Schulcloud
SC_CONTACT_EMAIL: schulcloud-support@thillm.de
GLOBAL_ANNOUNCEMENT_TEXT: ''
GLOBAL_ANNOUNCEMENT_ROLES: teacher,administrator
TRAINING_URL: "https://www.schulportal-thueringen.de/tio"

TEACHER_VISIBILITY_FOR_EXTERNAL_TEAM_INVITATION: opt-in
STUDENT_TEAM_CREATION: "opt-in"

# FEATURE TOGGLE
FEATURE_MULTIPLE_S3_PROVIDERS_ENABLED: "true"
FEATURE_S3_BUCKET_CORS: "false"
FEATURE_VIDEOCONFERENCE_WAITING_ROOM_ENABLED: "false"
FEATURE_TSP_AUTO_CONSENT_ENABLED: "true"
FEATURE_OAUTH_LOGIN_ENABLED: "false"
FEATURE_TEAMS_INVITE_EXTERNAL_ENABLED: "false"
FEATURE_DASHBOARD_DEFAULT_PICTURE_ENABLED: "false"
FEATURE_DASHBOARD_NEWS_ON_TOP_ENABLED: "true"
FEATURE_BOARD_READERS_CAN_EDIT_TOGGLE: "true"

TEACHER_STUDENT_VISIBILITY__IS_VISIBLE: "false"

# ADMIN TABLES
ADMIN_TABLES_DISPLAY_CONSENT_COLUMN: "false"
DISPLAY_REQUEST_LEVEL: -1
CONTENT_URI: https://content.schulcloud-thueringen.de

SERVER_LDAP_SYNC_FULL_CRONJOB: "0 */1 * * *"

# PORTS
PORT_SERVER: 3030
PORT_FILE_SERVICE: 4444
PORT_METRICS_SERVER: 9090

# Identity Management
IDENTITY_MANAGEMENT__TENANT: "{{ SC_THEME }}"
IDENTITY_MANAGEMENT__CLIENTID: "{{ SC_THEME }}"

# accessibility
ACCESSIBILITY_REPORT_EMAIL: institut@thillm.de

# BigBlueButton
VIDEOCONFERENCE_DEFAULT_PRESENTATION: https://{{ DOMAIN }}/bbb-presentation.pdf

# Nextcloud
COLLABORATIVE_STORAGE_PROVIDER: Nextcloud
NEXTCLOUD_SOCIALLOGIN_OIDC_INTERNAL_NAME: SchulcloudNextcloud
FEATURE_NEXTCLOUD_TEAM_FILES_ENABLED: "false"
NEXTCLOUD_SCOPES: "openid offline profile email groups"

WITH_BRANCH_TSP_REDIRECT_MANAGEMENT: true
INCLUDE_MAIL_IN_USER_FULL_TEXT_INDEX: "false"
