SC_THEME: thr
SC_TITLE: Th端ringer Schulcloud
SC_PRODUCTNAME: Th端ringer Schulcloud
SC_NAV_TITLE: Th端ringer Schulcloud
SC_CONTACT_EMAIL: schulcloud-support@thillm.de
GLOBAL_ANNOUNCEMENT_TEXT: ''
GLOBAL_ANNOUNCEMENT_ROLES: teacher,administrator

TEACHER_VISIBILITY_FOR_EXTERNAL_TEAM_INVITATION: opt-in
STUDENT_TEAM_CREATION: disabled
CORS: "true"
SECURITY_HEADERS: "true"

# FEATURE TOGGLES
ROCKETCHAT_SERVICE_ENABLED: "true"
FEATURE_CONTACT_FORM_ATTACHMENTS_ENABLED: "true"
FEATURE_ENTERTHECLOUD: "false"
FEATURE_EXTENSIONS_ENABLED: "false"
FEATURE_MINT_PAGES_ENABLED: "false"
FEATURE_MULTIPLE_S3_PROVIDERS_ENABLED: "true"
FEATURE_S3_BUCKET_CORS: "false"
FEATURE_TEAMS_ENABLED: "true"
FEATURE_VIDEOCONFERENCE_ENABLED: "true"
FEATURE_VIDEOCONFERENCE_WAITING_ROOM_ENABLED: "false"
FEATURE_TSP_AUTO_CONSENT_ENABLED: "true"
FEATURE_LOG_REQUEST: "false"
FEATURE_NUXT_SCHOOL_ADMIN_BETA: "true"
FEATURE_OAUTH_LOGIN_ENABLED: "false"
FEATURE_TEAMS_INVITE_EXTERNAL_ENABLED: "false"
FEATURE_LERNSTORE_ENABLED: "true"
FEATURE_ES_COLLECTIONS_ENABLED: "true"
FEATURE_ES_SEARCHABLE_ENABLED: "true"
FEATURE_ES_MERLIN_ENABLED: "true"
FEATURE_DASHBOARD_DEFAULT_PICTURE_ENABLED: "false"
FEATURE_DASHBOARD_NEWS_ON_TOP_ENABLED: "true"
TEACHER_STUDENT_VISIBILITY__IS_VISIBLE: "false"

# ADMIN TABLES
ADMIN_TABLES_DISPLAY_CONSENT_COLUMN: "false"
AWS_REGION: eu-central-1
STORAGE_SIGNED_URL_EXPIRE: 600
DISPLAY_REQUEST_LEVEL: -1
CONTENT_URI: https://content.schulcloud-thueringen.de

SERVER_LDAP_SYNC_FULL_CRONJOB: "0 */1 * * *"
JWT_TIMEOUT_SECONDS: 7200
JWT_SHOW_TIMEOUT_WARNING_SECONDS: 3600
DISABLED_BRUTE_FORCE_CHECK: "true"

# PORTS
PORT_SERVER: 3030
PORT_FILE_SERVICE: 4444
PORT_METRICS_SERVER: 9090

# TSP (Th端ringer Schulportal)
FEATURE_TSP_ENABLED: "true"

# Identity Management
IDENTITY_MANAGEMENT__TENANT: "{{ SC_THEME }}"
IDENTITY_MANAGEMENT__CLIENTID: "{{ SC_THEME }}"

# accessibility
ACCESSIBILITY_REPORT_EMAIL: institut@thillm.de

ES_MERLIN_AUTH_URL: http://merlin.nibis.de/auth.php

# BigBlueButton
VIDEOCONFERENCE_DEFAULT_PRESENTATION: https://s3.hidrive.strato.com/cloud-instances/thr/bbb/presentation.pdf

# Nextcloud
COLLABORATIVE_STORAGE_PROVIDER: Nextcloud
NEXTCLOUD_SOCIALLOGIN_OIDC_INTERNAL_NAME: SchulcloudNextcloud
FEATURE_NEXTCLOUD_TEAM_FILES_ENABLED: "false"
NEXTCLOUD_SCOPES: "openid offline profile email groups"

WITH_TSP: true