SCHULCLOUD_SERVER_IMAGE_TAG: 33.24.0
SCHULCLOUD_CLIENT_IMAGE_TAG: 33.24.0
NUXT_CLIENT_IMAGE_TAG: 33.24.1
SUPERHERO_DASHBOARD_IMAGE_TAG: 33.24.0
SCHULCLOUD_CALENDAR_IMAGE_TAG: 33.22.0
ANTIVIRUS_CHECK_SERVICE_IMAGE_TAG: 33.18.0
VERSION_AGGREGATOR_IMAGE_TAG: 33.18.0
H5P_STATICFILES_SERVER_IMAGE_TAG: 33.18.0
TLDRAW_CLIENT_IMAGE_TAG: 33.24.0
TLDRAW_SERVER_IMAGE_TAG: 33.24.0
FILE_STORAGE_IMAGE_TAG: 33.24.0
