FEATURE_COMMON_CARTRIDGE_COURSE_EXPORT_ENABLED: "true"
FEATURE_COMMON_CARTRIDGE_COURSE_IMPORT_ENABLED: "true"
FEATURE_ALLOW_INSECURE_LDAP_URL_ENABLED: "true"
H5P_FRAME_SRC_URLS: "https://rendering.edu-2.services.sc-dev-edusharing.dbildungscloud.dev/ https://rendering.services.sc-dev-edusharing.dbildungscloud.dev/"
BETTERMARKS_APPS_URL: "https://apps-ci00.bettermarks.com"
BETTERMARKS_SCHOOL_URL: "https://acc.bettermarks.com"

SC_DEFAULT_STORAGE_CLASS_NAME: "ionos-enterprise-hdd"

WITH_MAILCATCHER: true
