WITH_MIGRATION_SYSTEMS: true
WITH_VIDIS_MEDIA_METADATA_SYNC: true
WITH_MEDIA_LICENSES: true
WITH_SCHULCONNEX_PROVISIONING: true
WITH_BILO_MEDIA_METADATA_SYNC: true
WITH_MOIN_SCHULE: true
WITH_BOARD_COLLABORATION: true
