SCHULCLOUD_SERVER_IMAGE_TAG: 33.27.1
SCHULCLOUD_CLIENT_IMAGE_TAG: 33.27.0
NUXT_CLIENT_IMAGE_TAG: 33.27.1
SUPERHERO_DASHBOARD_IMAGE_TAG: 33.27.0
SCHULCLOUD_CALENDAR_IMAGE_TAG: 33.27.0
ANTIVIRUS_CHECK_SERVICE_IMAGE_TAG: 33.27.0
VERSION_AGGREGATOR_IMAGE_TAG: 33.27.0
H5P_STATICFILES_SERVER_IMAGE_TAG: 33.27.0
TLDRAW_CLIENT_IMAGE_TAG: 33.27.0
TLDRAW_SERVER_IMAGE_TAG: 33.27.0
FILE_STORAGE_IMAGE_TAG: 33.27.0
