---
- name: App Deploy
  hosts:
    - develop
  connection: local
  roles:
    - sys
    - pre_deployment
    - keda
    - namespace-activator-scaled-objects
    - external-secrets
    - dof_mongo
    - dof_mongo_management
    - dof_postgresql
    - dof_postgresql_management
    - dof_tsp_keycloak_management
    - dof_rabbitmq
    - dof_mailcatcher
    - collabora-office
    - libreoffice
    - maildrop
    - storage
    - hydra
    - erwin-idm
    - oidcmock
    - dof_etherpad
    - clamav
    - schulcloud-server-core
    - schulcloud-server-init
    - schulcloud-server-ldapsync
    - schulcloud-server-tspsync
    - schulcloud-server-h5p
    - schulcloud-server-migration-system
    - schulcloud-server-provisioning
    - schulcloud-client-core
    - session-valkey
    - nuxt-client-core
    - superhero-dashboard
    - schulcloud-calendar-core
    - schulcloud-calendar-init
    - h5p-library-management
    - fwu
    - h5p-proxy
    - clammit
    - h5p-staticfiles-server-core
    - antivirus_check_service
    - version-aggregator
    - rocketchat
    - mongodb_query_exporter
    - tldraw-client-core
    - tldraw-server
    - tldraw-valkey
    - common-cartridge
    - ingress
    - post_deployment
    - moin-schule-sync
    - media-licenses
    - bilo-media-metadata-sync
    - vidis-media-metadata-sync
    - file-storage
